apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example-app
spec:
  containers:
    - name: example-container
      image: nginx     # Replace with "node:14" if using a Node.js app
      ports:
        - containerPort: 80
