apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: nginx-app       # For Nginx, or use `nodejs-app` for Node.js
  ports:
    - protocol: TCP
      port: 3000           # Use 3000 if it's a Node.js app
      targetPort: 3000      # Use 3000 if it's a Node.js app
  type: NodePort
