apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001    # Optional: Specify a NodePort (range: 30000-32767)
  type: NodePort
